import { Links } from 'components/Links'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Storybook with Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Awesome Title!</h1>
        <Links />
      </main>
    </div>
  )
}
